export type FeatureGroupKey = 'core' | 'auth' | 'admin' | 'system';

export type FeatureManifestEntry = {
  id: string;
  title: string;
  path: string;
  group: FeatureGroupKey;
  summary: string;
  api: string[];
  tags: string[];
  mobileGoals: string[];
  acceptance: string[];
};

export const featureGroups: { key: FeatureGroupKey; label: string; description: string }[] = [
  { key: 'core', label: 'Core Drive', description: '파일 탐색과 일상 사용 흐름' },
  { key: 'auth', label: 'Auth & Onboarding', description: '모바일 진입, 초대, 초기 설정' },
  { key: 'admin', label: 'Admin & Operations', description: '운영, 저장소, 마이그레이션, 보안' },
  { key: 'system', label: 'System & Status', description: '성능, 상태, 유지보수 시야' },
];

export const featureManifest: FeatureManifestEntry[] = [
  {
    id: 'files',
    title: '파일 탐색기',
    path: '/files',
    group: 'core',
    summary: '폴더 트리, breadcrumb, 목록/그리드 전환, node 이동의 모바일 축입니다.',
    api: ['GET /nodes/{id}', 'GET /nodes/{id}/children', 'GET /nodes/{id}/breadcrumb'],
    tags: ['tree', 'browse', 'mobile-core'],
    mobileGoals: ['한 손 탐색 가능한 목록 구조', 'breadcrumb 축약', '하단 액션 시트'],
    acceptance: ['모바일에서 폴더 이동이 가능해야 한다.', 'list/grid 전환이 좁은 폭에서도 유지돼야 한다.'],
  },
  {
    id: 'recent',
    title: '최근 항목',
    path: '/recent',
    group: 'core',
    summary: '최근 열람/수정 파일에 빠르게 다시 접근하는 화면입니다.',
    api: ['GET /nodes/{id}', 'GET /nodes/{id}/children'],
    tags: ['recent', 'shortcut'],
    mobileGoals: ['최근 항목을 홈에서 바로 진입', '썸네일과 변경 시각 우선'],
    acceptance: ['최근 항목 목록이 모바일 카드 형태로 보인다.'],
  },
  {
    id: 'favorites',
    title: '즐겨찾기',
    path: '/favorites',
    group: 'core',
    summary: '자주 여는 파일/폴더를 빠르게 고정하는 공간입니다.',
    api: ['GET /nodes/{id}', 'GET /nodes/{id}/children'],
    tags: ['favorites', 'shortcut'],
    mobileGoals: ['고정 항목 빠른 접근', '최근 항목과 구분되는 핀 보관함'],
    acceptance: ['즐겨찾기 목록은 모바일에서 별도 탭으로 접근 가능해야 한다.'],
  },
  {
    id: 'shared',
    title: '공유 링크',
    path: '/shared',
    group: 'core',
    summary: '읽기/쓰기 공유 링크와 공개 접근 흐름을 관리합니다.',
    api: ['POST /nodes/{id}/share-links', 'GET /nodes/{id}/share-links', 'GET /s/{token}'],
    tags: ['share', 'public-access'],
    mobileGoals: ['모바일에서 링크 생성/복사', '만료와 비밀번호 상태 확인'],
    acceptance: ['공유 링크 상태와 권한이 한 화면에서 보여야 한다.'],
  },
  {
    id: 'media',
    title: '미디어',
    path: '/media',
    group: 'core',
    summary: '썸네일과 미디어 브라우징을 모바일 갤러리 중심으로 재구성합니다.',
    api: ['GET /media/{id}/thumbnail'],
    tags: ['media', 'thumbnail', 'gallery'],
    mobileGoals: ['세로 스크롤 갤러리', '빠른 preview', '썸네일 fallback'],
    acceptance: ['좁은 화면에서 썸네일 그리드가 유지돼야 한다.'],
  },
  {
    id: 'search',
    title: '검색',
    path: '/search',
    group: 'core',
    summary: '파일명과 메타데이터를 빠르게 찾는 모바일 검색 표면입니다.',
    api: ['GET /search'],
    tags: ['search', 'pg_trgm'],
    mobileGoals: ['상단 고정 검색 입력', '최근 검색', '결과 액션 시트'],
    acceptance: ['검색 입력과 결과 목록이 모바일 첫 화면에서 사용 가능해야 한다.'],
  },
  {
    id: 'trash',
    title: '휴지통',
    path: '/trash',
    group: 'core',
    summary: 'soft-delete, 복원, 영구 삭제를 다루는 공간입니다.',
    api: ['GET /trash', 'POST /trash/{id}/restore', 'DELETE /trash/{id}'],
    tags: ['trash', 'restore', 'delete'],
    mobileGoals: ['복원/영구삭제를 하단 sheet로 분리', '실수 방지용 확인 흐름'],
    acceptance: ['삭제와 복원 액션이 모바일에서 분리돼야 한다.'],
  },
  {
    id: 'login',
    title: '로그인',
    path: '/login',
    group: 'auth',
    summary: '기존 Bento 인증 진입점의 모바일 버전입니다.',
    api: ['POST /auth/login', 'POST /auth/refresh', 'POST /auth/logout'],
    tags: ['auth', 'session'],
    mobileGoals: ['입력 최소화', '생체 인증 확장 여지', '세션 복구'],
    acceptance: ['모바일 입력 폼과 오류 피드백이 명확해야 한다.'],
  },
  {
    id: 'setup',
    title: '초기 설정',
    path: '/setup',
    group: 'auth',
    summary: '최초 admin 생성과 설치 완료 흐름입니다.',
    api: ['GET /setup/status', 'POST /setup/admin'],
    tags: ['setup', 'admin'],
    mobileGoals: ['단계형 생성 플로우', '필수 항목 최소화'],
    acceptance: ['setup_required 상태를 모바일에서도 처리할 수 있어야 한다.'],
  },
  {
    id: 'invite-accept',
    title: '초대 수락',
    path: '/invite/accept',
    group: 'auth',
    summary: '초대 토큰 기반 사용자 가입 흐름입니다.',
    api: ['POST /auth/accept-invite'],
    tags: ['invite', 'onboarding'],
    mobileGoals: ['토큰 확인, 비밀번호 설정, 완료 안내를 한 흐름으로'],
    acceptance: ['모바일에서 초대 수락이 완료 가능해야 한다.'],
  },
  {
    id: 'admin',
    title: '관리 개요',
    path: '/admin',
    group: 'admin',
    summary: '관리 기능 허브와 운영 탭 진입점입니다.',
    api: ['GET /admin/users', 'GET /admin/volumes', 'GET /jobs'],
    tags: ['admin', 'hub'],
    mobileGoals: ['섹션별 quick links', '운영 우선순위 정리'],
    acceptance: ['모바일에서 admin 각 기능으로 이동 가능해야 한다.'],
  },
  {
    id: 'admin-users',
    title: '사용자 관리',
    path: '/admin/users',
    group: 'admin',
    summary: '유저, 초대, 권한의 관리 표면입니다.',
    api: ['GET /admin/users', 'POST /admin/users', 'POST /admin/invites', 'GET /admin/invites'],
    tags: ['users', 'invites'],
    mobileGoals: ['초대 생성과 사용자 상태 확인', '작은 화면용 관리자 리스트'],
    acceptance: ['유저/초대 리스트가 모바일 카드 레이아웃으로 보인다.'],
  },
  {
    id: 'admin-storage',
    title: '스토리지 관리',
    path: '/admin/storage',
    group: 'admin',
    summary: '볼륨 등록, 활성화, 검증, 정리 기능입니다.',
    api: ['POST /admin/volumes/validate-path', 'GET /admin/volumes', 'POST /admin/volumes', 'POST /admin/volumes/{id}/activate', 'PATCH /admin/system-mode'],
    tags: ['storage', 'volumes', 'readonly'],
    mobileGoals: ['읽기 전용 모드와 볼륨 상태를 한 화면에서 확인'],
    acceptance: ['읽기 전용 상태와 볼륨 상태가 모바일에서 확인 가능해야 한다.'],
  },
  {
    id: 'admin-migration',
    title: '마이그레이션',
    path: '/admin/migration',
    group: 'admin',
    summary: 'blob 이동과 검증 작업을 관리합니다.',
    api: ['POST /admin/migrations', 'GET /jobs', 'GET /jobs/{id}'],
    tags: ['migration', 'jobs'],
    mobileGoals: ['작업 큐 상태와 진행률 우선 표시'],
    acceptance: ['마이그레이션 시작과 상태 확인 흐름이 분리돼야 한다.'],
  },
  {
    id: 'admin-performance',
    title: '성능',
    path: '/admin/performance',
    group: 'admin',
    summary: 'QoS와 pressure metrics 상태를 봅니다.',
    api: ['GET /system/performance'],
    tags: ['qos', 'performance'],
    mobileGoals: ['핵심 메트릭 요약', '프로파일 전환 여지'],
    acceptance: ['성능 프로파일과 핵심 상태가 모바일에서 읽혀야 한다.'],
  },
  {
    id: 'admin-jobs',
    title: '작업',
    path: '/admin/jobs',
    group: 'admin',
    summary: '백그라운드 작업 상태와 유형 필터링 화면입니다.',
    api: ['GET /jobs', 'GET /jobs/{id}'],
    tags: ['jobs', 'background'],
    mobileGoals: ['유형 필터와 상태 요약', '실패 작업 우선 노출'],
    acceptance: ['모바일에서 작업 상태를 스크롤 가능한 카드로 본다.'],
  },
  {
    id: 'admin-audit',
    title: '감사 로그',
    path: '/admin/audit',
    group: 'admin',
    summary: '운영 변경과 접근 이력을 추적하는 화면입니다.',
    api: ['GET /admin/users'],
    tags: ['audit', 'ops'],
    mobileGoals: ['최근 위험 이벤트 우선 표시'],
    acceptance: ['감사 로그 화면이 별도 라우트로 존재해야 한다.'],
  },
  {
    id: 'admin-security',
    title: '보안',
    path: '/admin/security',
    group: 'admin',
    summary: 'ACL, 공유 정책, 보안 상태를 다룹니다.',
    api: ['GET /nodes/{id}/acl', 'PUT /nodes/{id}/acl', 'GET /nodes/{id}/access'],
    tags: ['security', 'acl'],
    mobileGoals: ['권한 상태 읽기 우선', '변경은 안전하게 분리'],
    acceptance: ['ACL 읽기 화면이 모바일에서 접근 가능해야 한다.'],
  },
  {
    id: 'admin-appearance',
    title: '표시 설정',
    path: '/admin/appearance',
    group: 'admin',
    summary: '향후 UI/브랜딩 설정을 위한 표면입니다.',
    api: ['PATCH /me/preferences'],
    tags: ['appearance', 'prefs'],
    mobileGoals: ['테마와 레이아웃 선호도 분리'],
    acceptance: ['모바일 설정 페이지의 구조가 준비돼야 한다.'],
  },
  {
    id: 'system-status',
    title: '시스템 상태',
    path: '/system/status',
    group: 'system',
    summary: 'health, version, capability를 모아 보는 모바일 운영 화면입니다.',
    api: ['GET /health', 'GET /system/version', 'GET /system/capabilities'],
    tags: ['health', 'capabilities'],
    mobileGoals: ['요약형 상태 카드', '운영자가 이동 중에도 읽을 수 있게'],
    acceptance: ['핵심 시스템 상태 라우트가 있어야 한다.'],
  },
];

export const homeFeatureIds = ['files', 'recent', 'shared', 'media', 'search', 'admin-jobs'];
